# Generated by Django 2.2.6 on 2019-11-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('genname', models.CharField(max_length=30)),
                ('bus', models.IntegerField()),
                ('busname', models.CharField(max_length=10)),
                ('Pmin', models.IntegerField()),
                ('Pmax', models.IntegerField()),
                ('minON', models.IntegerField()),
                ('minOFF', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('IntHour', models.IntegerField()),
                ('IntPow', models.FloatField()),
                ('SUCost', models.FloatField()),
                ('SDCost', models.FloatField()),
                ('NOLOADCOST', models.FloatField()),
                ('k1', models.FloatField()),
                ('SP1', models.IntegerField()),
                ('k2', models.FloatField()),
                ('SP2', models.IntegerField()),
                ('k3', models.FloatField()),
                ('SP3', models.IntegerField()),
                ('k4', models.FloatField()),
                ('SP4', models.IntegerField()),
                ('RAMP_RATE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Info2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B1', models.FloatField()),
                ('B2', models.FloatField()),
                ('B3', models.FloatField()),
                ('B11', models.FloatField()),
                ('B12', models.FloatField()),
                ('B13', models.FloatField()),
                ('B14', models.FloatField()),
                ('B21', models.FloatField()),
                ('B22', models.FloatField()),
                ('B23', models.FloatField()),
                ('B24', models.FloatField()),
                ('B31', models.FloatField()),
                ('B32', models.FloatField()),
                ('B33', models.FloatField()),
                ('B101', models.FloatField()),
                ('B111', models.FloatField()),
                ('B231', models.FloatField()),
                ('B311', models.FloatField()),
            ],
        ),
    ]
