from django.db import models

# Create your models here.
class Info1(models.Model):
    number = models.CharField(max_length=30)
    genname = models.CharField(max_length=30)
    bus = models.CharField(max_length=30)
    busname = models.CharField(max_length=30)
    Pmin = models.CharField(max_length=30)
    Pmax = models.CharField(max_length=30)
    minON = models.CharField(max_length=30)
    minOFF = models.CharField(max_length=30)
    Status = models.CharField(max_length=30)
    IntHour = models.CharField(max_length=30)
    IntPow = models.CharField(max_length=30)
    SUCost = models.CharField(max_length=30)
    SDCost = models.CharField(max_length=30)
    NOLOADCOST = models.CharField(max_length=30)
    k1 = models.CharField(max_length=30)
    SP1 = models.CharField(max_length=30)
    k2 = models.CharField(max_length=30)
    SP2 = models.CharField(max_length=30)
    k3 = models.CharField(max_length=30)
    SP3 = models.CharField(max_length=30)
    k4 = models.CharField(max_length=30)
    SP4 = models.CharField(max_length=30)
    RAMP_RATE = models.CharField(max_length=30)


class Info2(models.Model):
    B1 = models.CharField(max_length=30)
    B2 = models.CharField(max_length=30)
    B3 = models.CharField(max_length=30)
    B11 = models.CharField(max_length=30)
    B12 = models.CharField(max_length=30)
    B13 = models.CharField(max_length=30)
    B14 = models.CharField(max_length=30)
    B21 = models.CharField(max_length=30)
    B22 = models.CharField(max_length=30)
    B23 = models.CharField(max_length=30)
    B24 = models.CharField(max_length=30)
    B31 = models.CharField(max_length=30)
    B32 = models.CharField(max_length=30)
    B33 = models.CharField(max_length=30)
    B101 = models.CharField(max_length=30)
    B111 = models.CharField(max_length=30)
    B231 = models.CharField(max_length=30)
    B311 = models.CharField(max_length=30)